#!/usr/bin/env bash

rm input.rb | true
files=$(grep require_relative lib/high_score.rb | gsed -En "s/require_relative\s+'(\w+\.rb)'/\1/p")

grep -v require_relative lib/high_score.rb >> high_score.rb

for file in ${files}
do
  cat "lib/${file}" >> high_score.rb
  echo "" >> high_score.rb
done
